name: build-workflow

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Trigger workflow in another repo
      uses: actions/github-script@v7
      with:
        script: |
          const clientPayload = { event_type: 'build_completed' };

          const response = await github.rest.repos.createDispatchEvent({
            owner: 'infopulse',
            repo: 'Playwright-course-python',
            event_type: 'on-demand-test',
            client_payload: {build : 'ok'},
          });

          console.log(response);
        token: ${{ secrets.REPO_ACCESS_TOKEN }}